### ISSUE TITLE
.form-group crops :focus on radio and checkbox

### ISSUE THREAD

**Issue by Demotive** [nhsuk/register-with-a-gp-beta-web#224]
When in a focussed state and a child of `.form-group` radio and checkbox elements have a cropped `:focus` style.

<img width="132" alt="screen shot 2017-07-24 at 10 42 07" src="https://user-images.githubusercontent.com/1913757/28517658-0543970a-705d-11e7-8207-319bf7eea037.png">

<img width="145" alt="screen shot 2017-07-24 at 10 44 32" src="https://user-images.githubusercontent.com/1913757/28517672-13a74d0a-705d-11e7-8cd4-0156b4dac7be.png">

It's caused by `overflow: auto;` on `.form-fields`

https://github.com/nhsuk/register-with-a-gp-beta-web/blob/master/src/client/styles/components/_form-group.scss

Which I think is inheriting `@clearfix` from the nhsuk-frontend

```
.form-fields {
    clear: left;
    overflow: auto;
}
```

**Comment by st3v3nhunt** [comment]
Closing this issue as the project is no longer active and it will not be worked on.
