### ISSUE TITLE
Reset cookie on start page

### ISSUE THREAD

**Issue by marcofucci** [nhsuk/register-with-a-gp-beta-web#36]
The `data` cookie should get destroyed when you are on the start page.
You should probably just add `unstate('data')` at this line https://github.com/nhsuk/register-with-a-gp-beta-web/blob/master/src/server/plugins/start-and-end/index.js#L14 and test.

**Comment by st3v3nhunt** [comment]
Closing this issue as the project is no longer active and it will not be worked on.
